### ISSUE TITLE
Report mutli geometries and geometry collections

### ISSUE THREAD

**Issue by perrygeo** [mapbox/geojson-summary#3]
Using [this geojson](https://gist.github.com/perrygeo/d28adb4bd9e88d38bbe6) containing all supported geometry types:

    "Point"
    "MultiPoint"
    "LineString"
    "Polygon"
    "MultiLineString"
    "MultiPolygon"
    "GeometryCollection"

The `geojson-summary` cli reports

    1 point, 1 polygon, and 1 line

**Comment by tmcw** [comment]
Err.. I'm going to split this into two tasks: multi types, and geometry collections. I don't know what English sentence would correctly describe GeometryCollections.

**Comment by tmcw** [comment]
0.4.0 adds multi support.

**Comment by perrygeo** [comment]
>  I don't know what English sentence would correctly describe GeometryCollections.

Yeah I just included that for completeness (I don't use them or see them too much in the wild). It's tricky as it does introduce a hierarchy and potential nesting which is difficult to describe. Maybe just avoid descending into the collection and report "2 geometry collections"?

**Comment by sgillies** [comment]
@tmcw how about something like "geometry collection... may the force be with you"
